name = "growth-record"
main = "src/worker/index.ts"
compatibility_date = "2026-05-07"
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "growth-record"
database_id = "a5a0a697-f26d-4c2e-b052-e97ed45fb80c"
